### ISSUE TITLE
Some problems with the note on nesting

### ISSUE THREAD

**Issue by amcooper** [learn-co-curriculum/sql-crowdfunding-lab#26]
- What is labeled 'Grocery schema' is not a schema, but the result of the query `select * from groceries;`
- This query result contains bananas instead of peaches.
- The numbers in the final query aren't correct. 

It's as though edits were envisioned for this section, but not all of them were actually made.

**Comment by maxwellbenton** [comment]
Hi @amcooper,

Thank you for opening this issue. We've recently updated this lesson and incorporated changes based on your feedback, removing the reference to schema, and replacing bananas with peaches. I was unable to find where the numbers are incorrect, but these may have been fixed in an earlier update. These changes should resolve this issue

Thank you for contributing to a Learn lesson!
