### ISSUE TITLE
Test for `selects_the_category_names_and_pledge_amounts_of_all_pledges_in_the_music_category` is ambiguous

### ISSUE THREAD

**Issue by DerekKaknes** [learn-co-curriculum/sql-crowdfunding-lab#27]
I'm stuck with a failing test for `selects_the_category_names_and_pledge_amounts_of_all_pledges_in_the_music_category` because the order of my results is different from those expected by the test.  However, I don't immediately see what order the expectation is in, so it is very difficult to map to it exactly.  I would recommend adding a specific `ORDER BY amount` clause to the test so that the results are no longer ambiguous.

**Comment by maxwellbenton** [comment]
Hi @DerekKaknes,

Thank you for opening this issue. We've recently updated this lesson's tests and incorporated changes based on your feedback. Since you provided a valid solution that just didn't happen to be in the correct order, we've updated the tests to accept either, which should resolve this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing to a Learn lesson!
