### ISSUE TITLE
test asks for ordering by two columns but actually only wants ordering by one column

### ISSUE THREAD

**Issue by jeremylenz** [learn-co-curriculum/sql-crowdfunding-lab#28]
The function

selects_user_names_and_amounts_of_all_pledges_grouped_by_name_then_orders_them_by_the_amount_and_users_name

is misleading because when you have SQL order them by both amount and name, the test fails.  However, when you order only by SUM(pledges.amount), the test passes.

**Comment by maxwellbenton** [comment]
Hi @jeremylenz,

Thank you for opening this issue. We've recently updated this lesson's tests and incorporated changes based on your feedback. Since you provided a valid solution that just didn't happen to be in the correct order, we've updated the tests to accept either, which should resolve this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing to a Learn lesson!
