### ISSUE TITLE
selects_the_titles_of_all_projects_and_their_pledge_amounts_alphabetized_by_name Query

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sql-crowdfunding-lab#31]
Hey, so on this method, the use of the word "name" is a little deceiving. The only time name is used is for users.name, so it appears that you need to do two joins--one to get the project titles and the pledge amounts and another to get the user names.

If you change the word "name" on this method to "title" that would make much more sense.

**Comment by maxwellbenton** [comment]
Hi @helloamandamurphy,

Thank you for opening this issue! We've recently updated this lesson and incorporated changes based on your feedback. The title of the first method has been changed so that it now says `title` rather than `name` to avoid confusion for future students.

Thank you for this contribution!
